name: textlint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: yarn install
      - name: install reviewdog
        run: curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s
      - name: lint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          files=$(git diff --diff-filter=d --name-only origin/master HEAD | grep .md || true)
          $(npm bin)/textlint -f checkstyle $files | ./bin/reviewdog -f=checkstyle -name=textlint -reporter=github-pr-review
